model_name: model_normal
describe: res320_stride8_hardaug_randomcrop_noela
path:
    test_dir: ../../s2_data/data/test
    model_dir: ../../user_data/model_data
    save_dir: ../../user_data/temp_npy
    resume_path : /data/dongchengbo/submit/user_data/model_data/model_normal/model_6.pt
    test_path: /data/dongchengbo/id_card_train_data/step1.txt

train:
    train_path: /data/dongchengbo/id_card_train_data/step2_train.txt
    val_path: /data/dongchengbo/id_card_train_data/step2_val.txt
    batchSize: 224
    imageSize: 256
    stride: 8
    lr: 0.001
    outf: ../../user_data/model_data
    writer_root: ../../user_data/tensorlog
    th: 0.25
    remove: 1
    aug: 1
    loss_type: 1111
    fp16: 1
    ela: 0
    random_crop: 1
    hard_aug: 0
    niter: 15
    step_save: 1
    save_step: 1
    resume: 1

test:
    batchSize: 224
    imageSize: 256
    stride: 8
    fp16: 1
    ela: 0
